language: php

php:
    - '7.4'

install:
    # Install Statamic CLI
    - composer global require statamic/cli

    # Install Statamic
    - cd ../..
    - ~/.config/composer/vendor/bin/statamic new statamic-addon-test --no-interaction
    - cd statamic-addon-test

    # Copy addon to site/addons
    - mkdir -p site/addons/Shopify
    - cp -R $TRAVIS_BUILD_DIR/* site/addons/Shopify
    - php please update:addons

    # Install dev dependencies to get php unit
    - cd statamic && composer install
    - cd ../

script:
    - statamic/vendor/bin/phpunit --group shopify
